spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.56.101
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx425947f54e41a408
  mpAppSecret: dc1a51b6ef532bc84f099c53057311e6
  openAppId: wx425947f54e41a408
  openAppSecret: dc1a51b6ef532bc84f099c53057311e6
  mchId: 1309146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://tianci.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

ProjectUrl:
  wechatMpAuthorize: http://tianci.natapp1.cc
  wechatOpenAuthorize: http://tianci.natapp1.cc
  sell: http://tianci.natapp1.cc
logging:
  level:
    com.tianci.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
